- name: Чтение из {{crontab_source}}
  command: cat "{{ app_path }}/{{crontab_source}}"
  register: crontab_content

- name: Создание .crontab
  template:
    src: crontab.j2
    dest: "{{app_basepath}}/{{app_release_name}}.crontab"
    owner: apache
    group: apache
    mode: "0600"
  vars:
    cronjobs: "{{ crontab_content.stdout | from_yaml }}"
    app_base_path: "{{app_basepath}}/{{app_release_name}}/"
    app_log_path: "/var/log/cleversite"